### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by syohex** [gfx/Perl-UNIVERSAL-DOES#1]
Would you release latest version to CPAN or give me comaint of this package and
access permission of this repository(I shall upload latest version instead of you) ?

I can't install some packages which use this package with Perl 5.18 or higher.
(I know that I can install those modules with `cpanm --notest` )

https://metacpan.org/requires/distribution/UNIVERSAL-DOES?sort=[[2,1]]

**Comment by gfx** [comment]
OMG. Now you can modify & release this module but in this case I has released it. Thanks.

**Comment by syohex** [comment]
Thanks. I confirmed install new version with Perl 5.18.0 or higher.

**Comment by martinpopel** [comment]
@gfx Thanks for the CPAN release (I've marked this bug as resolved on rt.cpan.org).
BTW: any chances to fix https://rt.cpan.org/Ticket/Display.html?id=74539 ?
What is the preferred bug tracker for PerlIO::Util ? Does it live on GitHub too?
