### ISSUE TITLE
Let does() test for Regexp overloading

### ISSUE THREAD

**Issue by bpj** [gfx/Perl-UNIVERSAL-DOES#2]
What about letting does() check for Regexp overloading?

**Comment by gfx** [comment]
Thanks for the request.

I'm not sure about what you want, but this module should provide exactly the same as Perl's built-in UNIVERSAL::DOES. I won't add features that built-in's doesn't have.

**Comment by bpj** [comment]
But there is no built-in `does(THING, ROLE|OVERLOAD)` function, is there? That's what I'm using.
So the stuff on [line 39][] and [line 66][] doesn't have anything to do with the DOES method, or does it? (No pun intended!)

I mean if I currently do this:

``````perl
use 5.010;
use strict;
use warnings;
use utf8;

package Foo;

use Carp;

use overload
    fallback => 1,
    '%{}' => sub { $_[0][0] },  # returns hash
    'qr'  => sub { $_[0][1] },  # returns regex
    ;

sub new {
    my($class, $hash) = @_;
    my $re = join '|', map { quotemeta $_ } sort { length($b) <=> length($a) } keys %$hash;
    return bless [ $hash, qr/$re/ ] => $class;
}

package main;

use UNIVERSAL::DOES qw[ does ];

my %mapping = (  # Not the actual data but similar
    "\x{2768}" => "\x{2769}",  # MEDIUM LEFT PARENTHESIS ORNAMENT
    "\x{2769}" => "\x{2768}",  # MEDIUM RIGHT PARENTHESIS ORNAMENT
    "\x{276A}" => "\x{276B}",  # MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT
    "\x{276B}" => "\x{276A}",  # MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT
    "\x{276C}" => "\x{276D}",  # MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT
    "\x{276D}" => "\x{276C}",  # MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
);

my $foo = Foo->new(\%mapping);

say does({},    'HASH'  );  # true
say does($foo,  'HASH'  );  # true
say does(qr/x/, 'Regexp');  # true
say does($foo,  'Regexp');  # false <-- this is the problem!
``````

I.e. `does($foo, 'Regexp')` returns false when `$foo` is an object with regex overloading!

I can't explain it any better than that!

[line 39]: https://github.com/gfx/Perl-UNIVERSAL-DOES/blob/master/lib/UNIVERSAL/DOES.pm#L39
[line 66]: https://github.com/gfx/Perl-UNIVERSAL-DOES/blob/master/lib/UNIVERSAL/DOES.pm#L66

**Comment by bpj** [comment]
I have a pull request ready, should you change your mind.
